import {
	AlertDirection,
	ClaimStatus,
	DevicePlatform,
	LastOrderStatus,
	NotificationChannel,
	NotificationStatus,
	NotificationType,
} from '@backend/common';

export const metadataSchema = {
	type: 'object',
	properties: {
		nextPage: { type: 'string', nullable: true },
	},
};

export const archivedMetadataSchema = {
	type: 'object',
	properties: {
		records: { type: 'integer', nullable: true },
		totalRecords: { type: 'integer', nullable: true },
		currentPage: { type: 'integer', nullable: true },
		totalPages: { type: 'integer', nullable: true },
		nextPage: { type: 'integer', nullable: true },
		includesLatest: { type: 'boolean', nullable: true },
	},
};

export const depositSchema = {
	type: 'object',
	properties: {
		ts: { type: 'integer' },
		txSig: { type: 'string' },
		txSigIndex: { type: 'integer' },
		slot: { type: 'integer' },
		amount: { type: 'string' },
		oraclePrice: { type: 'string' },
		marketDepositBalance: { type: 'string' },
		marketWithdrawBalance: { type: 'string' },
		marketCumulativeDepositInterest: { type: 'string' },
		marketCumulativeBorrowInterest: { type: 'string' },
		totalDepositsAfter: { type: 'string' },
		totalWithdrawsAfter: { type: 'string' },
		depositRecordId: { type: 'string' },
		userAuthority: { type: 'string' },
		user: { type: 'string' },
		direction: { type: 'string' },
		explanation: { type: 'string' },
		marketIndex: { type: 'integer' },
		symbol: { type: 'string' },
	},
	required: [
		'ts',
		'txSig',
		'txSigIndex',
		'slot',
		'amount',
		'oraclePrice',
		'marketDepositBalance',
		'marketWithdrawBalance',
		'marketCumulativeDepositInterest',
		'marketCumulativeBorrowInterest',
		'totalDepositsAfter',
		'totalWithdrawsAfter',
		'depositRecordId',
		'userAuthority',
		'user',
		'direction',
		'marketIndex',
		'explanation',
	],
} as const;

export const settlePnlSchema = {
	type: 'object',
	properties: {
		ts: { type: 'integer' },
		txSig: { type: 'string' },
		txSigIndex: { type: 'integer' },
		slot: { type: 'integer' },
		pnl: { type: 'string' },
		user: { type: 'string' },
		baseAssetAmount: { type: 'string' },
		quoteAssetAmountAfter: { type: 'string' },
		quoteEntryAmount: { type: 'string' },
		settlePrice: { type: 'string' },
		marketIndex: { type: 'integer' },
		explanation: { type: 'string' },
	},
	required: [
		'ts',
		'txSig',
		'txSigIndex',
		'slot',
		'pnl',
		'user',
		'baseAssetAmount',
		'quoteAssetAmountAfter',
		'quoteEntryAmount',
		'settlePrice',
		'marketIndex',
		'explanation',
	],
} as const;

export const fundingPaymentSchema = {
	type: 'object',
	properties: {
		ts: { type: 'integer' },
		txSig: { type: 'string' },
		txSigIndex: { type: 'integer' },
		slot: { type: 'integer' },
		userAuthority: { type: 'string' },
		user: { type: 'string' },
		marketIndex: { type: 'integer' },
		fundingPayment: { type: 'string' },
		baseAssetAmount: { type: 'string' },
		userLastCumulativeFunding: { type: 'string' },
		ammCumulativeFundingLong: { type: 'string' },
		ammCumulativeFundingShort: { type: 'string' },
	},
	required: [
		'ts',
		'txSig',
		'txSigIndex',
		'slot',
		'userAuthority',
		'user',
		'marketIndex',
		'fundingPayment',
		'baseAssetAmount',
		'userLastCumulativeFunding',
		'ammCumulativeFundingLong',
		'ammCumulativeFundingShort',
	],
} as const;

export const liquidationSchema = {
	type: 'object',
	properties: {
		ts: { type: 'integer' },
		txSig: { type: 'string' },
		txSigIndex: { type: 'integer' },
		slot: { type: 'integer' },
		liquidationType: { type: 'string' },
		user: { type: 'string' },
		liquidator: { type: 'string' },
		marginRequirement: { type: 'string' },
		totalCollateral: { type: 'string' },
		marginFreed: { type: 'string' },
		liquidationId: { type: 'string' },
		bankrupt: { type: 'boolean' },
		canceledOrderIds: { type: 'array', items: { type: 'string' } },
		liquidatePerp_marketIndex: { type: 'integer' },
		liquidatePerp_oraclePrice: { type: 'string' },
		liquidatePerp_baseAssetAmount: { type: 'string' },
		liquidatePerp_quoteAssetAmount: { type: 'string' },
		liquidatePerp_lpShares: { type: 'string' },
		liquidatePerp_fillRecordId: { type: 'string' },
		liquidatePerp_userOrderId: { type: 'string' },
		liquidatePerp_liquidatorOrderId: { type: 'string' },
		liquidatePerp_liquidatorFee: { type: 'string' },
		liquidatePerp_ifFee: { type: 'string' },
		liquidateSpot_assetMarketIndex: { type: 'integer' },
		liquidateSpot_assetPrice: { type: 'string' },
		liquidateSpot_assetTransfer: { type: 'string' },
		liquidateSpot_liabilityMarketIndex: { type: 'integer' },
		liquidateSpot_liabilityPrice: { type: 'string' },
		liquidateSpot_liabilityTransfer: { type: 'string' },
		liquidateSpot_ifFee: { type: 'string' },
		liquidateBorrowForPerpPnl_perpMarketIndex: { type: 'integer' },
		liquidateBorrowForPerpPnl_marketOraclePrice: { type: 'string' },
		liquidateBorrowForPerpPnl_pnlTransfer: { type: 'string' },
		liquidateBorrowForPerpPnl_liabilityMarketIndex: { type: 'integer' },
		liquidateBorrowForPerpPnl_liabilityPrice: { type: 'string' },
		liquidateBorrowForPerpPnl_liabilityTransfer: { type: 'string' },
		liquidatePerpPnlForDeposit_perpMarketIndex: { type: 'integer' },
		liquidatePerpPnlForDeposit_marketOraclePrice: { type: 'string' },
		liquidatePerpPnlForDeposit_pnlTransfer: { type: 'string' },
		liquidatePerpPnlForDeposit_assetMarketIndex: { type: 'integer' },
		liquidatePerpPnlForDeposit_assetPrice: { type: 'string' },
		liquidatePerpPnlForDeposit_assetTransfer: { type: 'string' },
		perpBankruptcy_marketIndex: { type: 'integer' },
		perpBankruptcy_pnl: { type: 'string' },
		perpBankruptcy_ifPayment: { type: 'string' },
		perpBankruptcy_clawbackUser: { type: 'string' },
		perpBankruptcy_clawbackUserPayment: { type: 'string' },
		perpBankruptcy_cumulativeFundingRateDelta: { type: 'string' },
		spotBankruptcy_marketIndex: { type: 'integer' },
		spotBankruptcy_borrowAmount: { type: 'string' },
		spotBankruptcy_ifPayment: { type: 'string' },
		spotBankruptcy_cumulativeDepositInterestDelta: { type: 'string' },
	},
	required: [
		'ts',
		'txSig',
		'txSigIndex',
		'slot',
		'liquidationType',
		'user',
		'liquidator',
		'marginRequirement',
		'totalCollateral',
		'marginFreed',
		'liquidationId',
		'bankrupt',
		'canceledOrderIds',
		'liquidatePerp_marketIndex',
		'liquidatePerp_oraclePrice',
		'liquidatePerp_baseAssetAmount',
		'liquidatePerp_quoteAssetAmount',
		'liquidatePerp_lpShares',
		'liquidatePerp_fillRecordId',
		'liquidatePerp_userOrderId',
		'liquidatePerp_liquidatorOrderId',
		'liquidatePerp_liquidatorFee',
		'liquidatePerp_ifFee',
		'liquidateSpot_assetMarketIndex',
		'liquidateSpot_assetPrice',
		'liquidateSpot_assetTransfer',
		'liquidateSpot_liabilityMarketIndex',
		'liquidateSpot_liabilityPrice',
		'liquidateSpot_liabilityTransfer',
		'liquidateSpot_ifFee',
		'liquidateBorrowForPerpPnl_perpMarketIndex',
		'liquidateBorrowForPerpPnl_marketOraclePrice',
		'liquidateBorrowForPerpPnl_pnlTransfer',
		'liquidateBorrowForPerpPnl_liabilityMarketIndex',
		'liquidateBorrowForPerpPnl_liabilityPrice',
		'liquidateBorrowForPerpPnl_liabilityTransfer',
		'liquidatePerpPnlForDeposit_perpMarketIndex',
		'liquidatePerpPnlForDeposit_marketOraclePrice',
		'liquidatePerpPnlForDeposit_pnlTransfer',
		'liquidatePerpPnlForDeposit_assetMarketIndex',
		'liquidatePerpPnlForDeposit_assetPrice',
		'liquidatePerpPnlForDeposit_assetTransfer',
		'perpBankruptcy_marketIndex',
		'perpBankruptcy_pnl',
		'perpBankruptcy_ifPayment',
		'perpBankruptcy_clawbackUser',
		'perpBankruptcy_clawbackUserPayment',
		'perpBankruptcy_cumulativeFundingRateDelta',
		'spotBankruptcy_marketIndex',
		'spotBankruptcy_borrowAmount',
		'spotBankruptcy_ifPayment',
		'spotBankruptcy_cumulativeDepositInterestDelta',
	],
} as const;

export const lpSchema = {
	type: 'object',
	properties: {
		ts: { type: 'integer' },
		txSig: { type: 'string' },
		txSigIndex: { type: 'integer' },
		slot: { type: 'integer' },
		user: { type: 'string' },
		action: { type: 'string' },
		marketIndex: { type: 'integer' },
		nShares: { type: 'string' },
		deltaBaseAssetAmount: { type: 'string' },
		deltaQuoteAssetAmount: { type: 'string' },
		pnl: { type: 'string' },
	},
	required: [
		'ts',
		'txSig',
		'txSigIndex',
		'slot',
		'user',
		'action',
		'marketIndex',
		'nShares',
		'deltaBaseAssetAmount',
		'deltaQuoteAssetAmount',
		'pnl',
	],
} as const;

export const lpMintRedeemSchema = {
	type: 'object',
	properties: {
		ts: { type: 'integer' },
		txSig: { type: 'string' },
		txSigIndex: { type: 'integer' },
		slot: { type: 'integer' },
		authority: { type: 'string' },
		amount: { type: 'string' },
		fee: { type: 'string' },
		spotMarketIndex: { type: 'integer' },
		oraclePrice: { type: 'string' },
		mint: { type: 'string' },
		lpAmount: { type: 'string' },
		lpFee: { type: 'string' },
		lpPrice: { type: 'string' },
		description: { type: 'integer' },
		constituentIndex: { type: 'integer' },
		mintRedeemId: { type: 'string' },
		lastAum: { type: 'string' },
		lastAumSlot: { type: 'integer' },
		inMarketCurrentWeight: { type: 'string' },
		inMarketTargetWeight: { type: 'string' },
		lpPool: { type: 'string' },
	},
	required: [
		'ts',
		'txSig',
		'txSigIndex',
		'slot',
		'authority',
		'amount',
		'fee',
		'spotMarketIndex',
		'oraclePrice',
		'mint',
		'lpAmount',
		'lpFee',
		'lpPrice',
		'description',
		'constituentIndex',
		'mintRedeemId',
		'lastAum',
		'lastAumSlot',
		'inMarketCurrentWeight',
		'inMarketTargetWeight',
		'lpPool',
	],
} as const;

export const insuranceFundStakeSchema = {
	type: 'object',
	properties: {
		ts: { type: 'integer' },
		txSig: { type: 'string' },
		txSigIndex: { type: 'integer' },
		slot: { type: 'integer' },
		amount: { type: 'string' },
		userAuthority: { type: 'string' },
		action: { type: 'string' },
		marketIndex: { type: 'integer' },
		symbol: { type: 'string' },
		ifSharesBefore: { type: 'string' },
		ifSharesAfter: { type: 'string' },
		userIfSharesBefore: { type: 'string' },
		userIfSharesAfter: { type: 'string' },
		totalIfSharesBefore: { type: 'string' },
		totalIfSharesAfter: { type: 'string' },
		insuranceVaultAmountBefore: { type: 'string' },
	},
	required: [
		'ts',
		'txSig',
		'txSigIndex',
		'slot',
		'amount',
		'userAuthority',
		'action',
		'marketIndex',
		'ifSharesBefore',
		'userIfSharesBefore',
		'totalIfSharesBefore',
		'ifSharesAfter',
		'userIfSharesAfter',
		'totalIfSharesAfter',
		'insuranceVaultAmountBefore',
	],
} as const;

export const orderActionSchema = {
	type: 'object',
	properties: {
		ts: { type: 'integer' },
		txSig: { type: 'string' },
		txSigIndex: { type: 'integer' },
		slot: { type: 'integer' },
		fillerReward: { type: 'string' },
		baseAssetAmountFilled: { type: 'string' },
		quoteAssetAmountFilled: { type: 'string' },
		takerFee: { type: 'string' },
		makerRebate: { type: 'string' },
		referrerReward: { type: 'string' },
		quoteAssetAmountSurplus: { type: 'string' },
		takerOrderBaseAssetAmount: { type: 'string' },
		takerOrderCumulativeBaseAssetAmountFilled: { type: 'string' },
		takerOrderCumulativeQuoteAssetAmountFilled: { type: 'string' },
		makerOrderBaseAssetAmount: { type: 'string' },
		makerOrderCumulativeBaseAssetAmountFilled: { type: 'string' },
		makerOrderCumulativeQuoteAssetAmountFilled: { type: 'string' },
		oraclePrice: { type: 'string' },
		makerFee: { type: 'string' },
		action: { type: 'string' },
		actionExplanation: { type: 'string' },
		marketIndex: { type: 'integer' },
		marketType: { type: 'string' },
		marketFilter: { type: 'string' },
		filler: { type: 'string' },
		fillRecordId: { type: 'string' },
		taker: { type: 'string' },
		takerOrderId: { type: 'string' },
		takerOrderDirection: { type: 'string' },
		maker: { type: 'string' },
		makerOrderId: { type: 'string' },
		makerOrderDirection: { type: 'string' },
		spotFulfillmentMethodFee: { type: 'string' },
		user: { type: 'string' },
		symbol: { type: 'string' },
		bitFlags: { type: 'number' },
		takerExistingQuoteEntryAmount: { type: 'string' },
		takerExistingBaseAssetAmount: { type: 'string' },
		makerExistingQuoteEntryAmount: { type: 'string' },
		makerExistingBaseAssetAmount: { type: 'string' },
	},
	required: [
		'ts',
		'txSig',
		'txSigIndex',
		'slot',
		'fillerReward',
		'baseAssetAmountFilled',
		'quoteAssetAmountFilled',
		'takerFee',
		'makerRebate',
		'referrerReward',
		'quoteAssetAmountSurplus',
		'takerOrderBaseAssetAmount',
		'takerOrderCumulativeBaseAssetAmountFilled',
		'takerOrderCumulativeQuoteAssetAmountFilled',
		'makerOrderBaseAssetAmount',
		'makerOrderCumulativeBaseAssetAmountFilled',
		'makerOrderCumulativeQuoteAssetAmountFilled',
		'oraclePrice',
		'makerFee',
		'action',
		'actionExplanation',
		'marketIndex',
		'marketType',
		'filler',
		'fillRecordId',
		'taker',
		'takerOrderId',
		'takerOrderDirection',
		'maker',
		'makerOrderId',
		'makerOrderDirection',
		'spotFulfillmentMethodFee',
	],
};

export const positionHistorySchema = {
	type: 'object',
	properties: {
		ts: { type: 'integer' },
		txSig: { type: 'string' },
		txSigIndex: { type: 'integer' },
		slot: { type: 'integer' },
		fillerReward: { type: 'string' },
		baseClosedForPnl: { type: 'string' },
		baseAssetAmountFilled: { type: 'string' },
		quoteAssetAmountFilled: { type: 'string' },
		takerFee: { type: 'string' },
		makerRebate: { type: 'string' },
		referrerReward: { type: 'string' },
		quoteAssetAmountSurplus: { type: 'string' },
		takerOrderBaseAssetAmount: { type: 'string' },
		takerOrderCumulativeBaseAssetAmountFilled: { type: 'string' },
		takerOrderCumulativeQuoteAssetAmountFilled: { type: 'string' },
		makerOrderBaseAssetAmount: { type: 'string' },
		makerOrderCumulativeBaseAssetAmountFilled: { type: 'string' },
		makerOrderCumulativeQuoteAssetAmountFilled: { type: 'string' },
		oraclePrice: { type: 'string' },
		makerFee: { type: 'string' },
		action: { type: 'string' },
		actionExplanation: { type: 'string' },
		marketIndex: { type: 'integer' },
		marketType: { type: 'string' },
		marketFilter: { type: 'string' },
		filler: { type: 'string' },
		fillRecordId: { type: 'string' },
		taker: { type: 'string' },
		takerOrderId: { type: 'string' },
		takerOrderDirection: { type: 'string' },
		maker: { type: 'string' },
		makerOrderId: { type: 'string' },
		makerOrderDirection: { type: 'string' },
		spotFulfillmentMethodFee: { type: 'string' },
		userFee: { type: 'string' },
		user: { type: 'string' },
		symbol: { type: 'string' },
		bitFlags: { type: 'number' },
		userExistingQuoteEntryAmount: { type: 'string' },
		userExistingBaseAssetAmount: { type: 'string' },
		takerExistingQuoteEntryAmount: { type: 'string' },
		takerExistingBaseAssetAmount: { type: 'string' },
		makerExistingQuoteEntryAmount: { type: 'string' },
		makerExistingBaseAssetAmount: { type: 'string' },
	},
	required: [
		'ts',
		'txSig',
		'txSigIndex',
		'slot',
		'fillerReward',
		'baseAssetAmountFilled',
		'quoteAssetAmountFilled',
		'takerFee',
		'makerRebate',
		'referrerReward',
		'quoteAssetAmountSurplus',
		'takerOrderBaseAssetAmount',
		'takerOrderCumulativeBaseAssetAmountFilled',
		'takerOrderCumulativeQuoteAssetAmountFilled',
		'makerOrderBaseAssetAmount',
		'makerOrderCumulativeBaseAssetAmountFilled',
		'makerOrderCumulativeQuoteAssetAmountFilled',
		'oraclePrice',
		'makerFee',
		'action',
		'actionExplanation',
		'marketIndex',
		'marketType',
		'filler',
		'fillRecordId',
		'taker',
		'takerOrderId',
		'takerOrderDirection',
		'maker',
		'makerOrderId',
		'makerOrderDirection',
		'spotFulfillmentMethodFee',
		'userFee',
		'baseClosedForPnl',
	],
};

export const fundingRateSchema = {
	$id: 'FundingRateRecord',
	type: 'object',
	properties: {
		ts: { type: 'integer' },
		txSig: { type: 'string' },
		txSigIndex: { type: 'integer' },
		slot: { type: 'integer' },
		recordId: { type: 'string' },
		marketIndex: { type: 'integer' },
		symbol: { type: 'string' },
		fundingRate: { type: 'string' },
		fundingRateLong: { type: 'string' },
		fundingRateShort: { type: 'string' },
		cumulativeFundingRateLong: { type: 'string' },
		cumulativeFundingRateShort: { type: 'string' },
		oraclePriceTwap: { type: 'string' },
		markPriceTwap: { type: 'string' },
		periodRevenue: { type: 'string' },
		baseAssetAmountWithAmm: { type: 'string' },
		baseAssetAmountWithUnsettledLp: { type: 'string' },
	},
	required: [
		'ts',
		'txSig',
		'txSigIndex',
		'slot',
		'recordId',
		'marketIndex',
		'symbol',
		'fundingRate',
		'fundingRateLong',
		'fundingRateShort',
		'cumulativeFundingRateLong',
		'cumulativeFundingRateShort',
		'oraclePriceTwap',
		'markPriceTwap',
		'periodRevenue',
		'baseAssetAmountWithAmm',
		'baseAssetAmountWithUnsettledLp',
	],
} as const;

export const insuranceFundSchema = {
	type: 'object',
	properties: {
		ts: { type: 'integer' },
		txSig: { type: 'string' },
		txSigIndex: { type: 'integer' },
		slot: { type: 'integer' },
		spotMarketIndex: { type: 'integer' },
		perpMarketIndex: { type: 'integer' },
		userIfFactor: { type: 'number' },
		totalIfFactor: { type: 'number' },
		symbol: { type: 'string' },
		vaultAmountBefore: { type: 'string' },
		insuranceVaultAmountBefore: { type: 'string' },
		totalIfSharesBefore: { type: 'string' },
		totalIfSharesAfter: { type: 'string' },
		amount: { type: 'string' },
	},
	required: [
		'ts',
		'txSig',
		'txSigIndex',
		'slot',
		'spotMarketIndex',
		'perpMarketIndex',
		'userIfFactor',
		'totalIfFactor',
		'symbol',
		'vaultAmountBefore',
		'insuranceVaultAmountBefore',
		'totalIfSharesBefore',
		'totalIfSharesAfter',
		'amount',
	],
} as const;

export const swapSchema = {
	type: 'object',
	properties: {
		ts: { type: 'number' },
		txSig: { type: 'string' },
		txSigIndex: { type: 'number' },
		slot: { type: 'number' },
		user: { type: 'string' },
		outMarketIndex: { type: 'number' },
		inMarketIndex: { type: 'number' },
		outSymbol: { type: 'string' },
		inSymbol: { type: 'string' },
		isInMarket: { type: 'boolean' },
		amountOut: { type: 'string' },
		amountIn: { type: 'string' },
		outOraclePrice: { type: 'string' },
		inOraclePrice: { type: 'string' },
		fee: { type: 'string' },
	},
	required: [
		'ts',
		'txSig',
		'txSigIndex',
		'slot',
		'user',
		'amountOut',
		'amountIn',
		'outMarketIndex',
		'inMarketIndex',
		'outOraclePrice',
		'inOraclePrice',
		'fee',
	],
	additionalProperties: false,
} as const;

export const orderSchema = {
	type: 'object',
	properties: {
		ts: { type: 'number' },
		txSig: { type: 'string' },
		txSigIndex: { type: 'number' },
		slot: { type: 'number' },
		user: { type: 'string' },
		status: { type: 'string' },
		orderType: { type: 'string' },
		marketType: { type: 'string' },
		marketFilter: { type: 'string' },
		orderId: { type: 'number' },
		userOrderId: { type: 'number' },
		marketIndex: { type: 'number' },
		price: { type: 'string' },
		baseAssetAmount: { type: 'string' },
		quoteAssetAmount: { type: 'string' },
		baseAssetAmountFilled: { type: 'string' },
		quoteAssetAmountFilled: { type: 'string' },
		direction: { type: 'string' },
		reduceOnly: { type: 'boolean' },
		triggerPrice: { type: 'string' },
		triggerCondition: { type: 'string' },
		existingPositionDirection: { type: 'string' },
		postOnly: { type: 'boolean' },
		immediateOrCancel: { type: 'boolean' },
		oraclePriceOffset: { type: 'string' },
		auctionDuration: { type: 'number' },
		auctionStartPrice: { type: 'string' },
		auctionEndPrice: { type: 'string' },
		maxTs: { type: 'number' },
		symbol: { type: 'string' },
		lastActionStatus: { type: 'string', enum: Object.values(LastOrderStatus) },
		lastActionExplanation: { type: 'string' },
		lastUpdatedTs: { type: 'number' },
		cumulativeFee: { type: 'string', nullable: true },
	},
	required: [
		'ts',
		'txSig',
		'txSigIndex',
		'slot',
		'user',
		'status',
		'orderType',
		'marketType',
		'orderId',
		'userOrderId',
		'marketIndex',
		'price',
		'baseAssetAmount',
		'quoteAssetAmount',
		'baseAssetAmountFilled',
		'quoteAssetAmountFilled',
		'direction',
		'reduceOnly',
		'triggerPrice',
		'triggerCondition',
		'existingPositionDirection',
		'postOnly',
		'immediateOrCancel',
		'oraclePriceOffset',
		'auctionDuration',
		'auctionStartPrice',
		'auctionEndPrice',
		'maxTs',
	],
} as const;

export const candleSchema = {
	type: 'object',
	properties: {
		ts: { type: 'integer' },
		fillOpen: { type: 'number' },
		fillHigh: { type: 'number' },
		fillClose: { type: 'number' },
		fillLow: { type: 'number' },
		oracleOpen: { type: 'number' },
		oracleHigh: { type: 'number' },
		oracleClose: { type: 'number' },
		oracleLow: { type: 'number' },
		quoteVolume: { type: 'number' },
		baseVolume: { type: 'number' },
	},
	required: [
		'ts',
		'fillOpen',
		'fillHigh',
		'fillClose',
		'fillLow',
		'oracleOpen',
		'oracleHigh',
		'oracleClose',
		'oracleLow',
		'quoteVolume',
		'baseVolume',
	],
} as const;

export const deviceSchema = {
	type: 'object',
	properties: {
		deviceId: { type: 'string' },
		token: { type: 'string' },
		platform: { type: 'string', enum: Object.values(DevicePlatform) },
	},
	required: ['deviceId'],
} as const;

export const alertSchema = {
	type: 'object',
	properties: {
		alertId: { type: 'string' },
		authorityId: { type: 'string' },
		symbol: { type: 'string' },
		targetPrice: { type: 'number' },
		direction: { type: 'string', enum: Object.values(AlertDirection) },
	},
	required: ['symbol', 'targetPrice', 'direction'],
} as const;

export const whitelistSchema = {
	type: 'object',
	properties: {
		whitelistId: { type: 'string' },
		authorityId: { type: 'string' },
		address: { type: 'string' },
		label: { type: 'string' },
		token: { type: 'string' },
		chainId: { type: 'string' },
	},
	required: ['whitelistId', 'authorityId', 'address', 'label', 'token', 'chainId'],
} as const;

export const notificationSchema = {
	type: 'object',
	properties: {
		notificationId: { type: 'string' },
		authorityId: { type: 'string' },
		title: { type: 'string' },
		body: { type: 'string' },
		type: {
			type: 'string',
			enum: Object.values(NotificationType),
		},
		status: {
			type: 'string',
			enum: Object.values(NotificationStatus),
		},
		channels: {
			type: 'array',
			items: {
				type: 'string',
				enum: Object.values(NotificationChannel),
			},
			minItems: 1,
			uniqueItems: true,
		},
		data: {
			type: 'object',
			additionalProperties: true,
		},
		sentAt: { type: 'number' },
		createdAt: { type: 'number' },
	},
	required: ['notificationId', 'authorityId', 'title', 'body', 'type', 'status'],
} as const;

export const notificationPreferencesSchema = {
	type: 'object',
	properties: {
		authorityId: { type: 'string' },
		pushOptOutTypes: {
			type: 'array',
			items: {
				type: 'string',
				enum: Object.values(NotificationType),
			},
			uniqueItems: true,
		},
	},
	required: ['authorityId', 'pushOptOutTypes'],
	additionalProperties: false,
} as const;

export const snapShotQuerySchema = {
	type: 'object',
	properties: {
		days: { type: 'number', minimum: 1, maximum: 100, default: 7 },
	},
};

export const vaultDepositorSnapshotSchema = {
	type: 'object',
	nullable: true,
	properties: {
		ts: { type: 'number' },
		vault: { type: 'string' },
		totalAccountValue: { type: 'string' },
		totalAccountBaseValue: { type: 'string' },
		netDeposits: { type: 'string' },
		marketIndex: { type: 'number' },
	},
	required: ['ts', 'vault', 'totalAccountValue', 'totalAccountBaseValue', 'marketIndex'],
} as const;

export const referralSnapshotSchema = {
	type: 'object',
	nullable: true,
	properties: {
		ts: { type: 'number' },
		referralRewards: { type: 'string' },
		referralCount: { type: 'string' },
		referredUsers: { type: 'array', items: { type: 'string' } },
		referredVolume30D: { type: 'string' },
	},
} as const;

export const tradeSnapshotSchema = {
	type: 'object',
	nullable: true,
	properties: {
		ts: { type: 'number' },
		accountBalance: { type: 'string' },
		unrealizedPnl: { type: 'string' },
		cumulativeRealizedPnl: { type: 'string' },
		unsettledPnl: { type: 'string' },
		cumulativeSettledPnl: { type: 'string' },
		cumulativeFunding: { type: 'string' },
		cumulativeFeePaid: { type: 'string' },
		cumulativeFeeRebate: { type: 'string' },
		cumulativeTakerVolume: { type: 'string' },
		cumulativeMakerVolume: { type: 'string' },
	},
} as const;

export const tradeSnapshotMetricsSchema = {
	type: 'object',
	nullable: true,
	properties: {
		cumulativeRealizedPnl: { type: 'string' },
		cumulativeMakerVolume: { type: 'string' },
		cumulativeTakerVolume: { type: 'string' },
		cumulativeFeePaid: { type: 'string' },
		cumulativeFeeRebate: { type: 'string' },
	},
} as const;

export const dlpSnapshotSchema = {
	type: 'object',
	nullable: true,
	properties: {
		ts: { type: 'number' },
		price: { type: 'string' },
		tvl: { type: 'string' },
	},
} as const;

export const earnSnapshotSchema = {
	type: 'object',
	nullable: true,
	properties: {
		ts: { type: 'number' },
		assets: {
			type: 'array',
			items: {
				type: 'object',
				properties: {
					marketIndex: { type: 'number' },
					balance: { type: 'string' },
					deposits: { type: 'string' },
					rewards: { type: 'string' },
					withdrawals: { type: 'string' },
					pnl: { type: 'string' },
					interestBaseValue: { type: 'string' },
					interestQuoteValue: { type: 'string' },
					oraclePrice: { type: 'string' },
				},
				required: [
					'marketIndex',
					'balance',
					'deposits',
					'withdrawals',
					'pnl',
					'interestBaseValue',
					'interestQuoteValue',
					'oraclePrice',
				],
			},
		},
	},
	required: ['ts', 'assets'],
} as const;

export const vaultSchema = {
	type: 'object',
	properties: {
		pubkey: { type: 'string' },
		manager: { type: 'string' },
		tokenAccount: { type: 'string' },
		userStats: { type: 'string' },
		user: { type: 'string' },
		delegate: { type: 'string' },
		liquidationDelegate: { type: 'string' },
		userShares: { type: 'string' },
		totalShares: { type: 'string' },
		sharesBase: { type: 'string' },
		lastFeeUpdateTs: { type: 'number' },
		liquidationStartTs: { type: 'number' },
		redeemPeriod: { type: 'number' },
		initTs: { type: 'number' },
		totalWithdrawRequested: { type: 'number' },
		maxTokens: { type: 'string' },
		netDeposits: { type: 'string' },
		totalDeposits: { type: 'string' },
		totalWithdraws: { type: 'string' },
		managerNetDeposits: { type: 'string' },
		managerTotalDeposits: { type: 'string' },
		managerTotalWithdraws: { type: 'string' },
		managerTotalFee: { type: 'string' },
		managerTotalProfitShare: { type: 'string' },
		lastManagerWithdrawRequest: {
			type: 'object',
			properties: {
				shares: { type: 'string' },
				value: { type: 'string' },
				ts: { type: 'string' },
			},
			required: ['shares', 'value', 'ts'],
		},
		minDepositAmount: { type: 'string' },
		profitShare: { type: 'string' },
		managementFee: { type: 'string' },
		hurdleRate: { type: 'string' },
		spotMarketIndex: { type: 'number' },
		permissioned: { type: 'boolean' },
	},
	required: [
		'pubkey',
		'manager',
		'tokenAccount',
		'userStats',
		'user',
		'delegate',
		'liquidationDelegate',
		'userShares',
		'totalShares',
		'sharesBase',
		'lastFeeUpdateTs',
		'liquidationStartTs',
		'redeemPeriod',
		'initTs',
		'totalWithdrawRequested',
		'maxTokens',
		'netDeposits',
		'totalDeposits',
		'totalWithdraws',
		'managerNetDeposits',
		'managerTotalDeposits',
		'managerTotalWithdraws',
		'managerTotalFee',
		'managerTotalProfitShare',
		'lastManagerWithdrawRequest',
		'minDepositAmount',
		'profitShare',
		'managementFee',
		'hurdleRate',
		'spotMarketIndex',
		'permissioned',
	],
} as const;

export const insuranceFundSwapSchema = {
	type: 'object',
	properties: {
		ts: { type: 'integer' },
		txSig: { type: 'string' },
		txSigIndex: { type: 'integer' },
		slot: { type: 'integer' },
		inMarketIndex: { type: 'integer' },
		outMarketIndex: { type: 'integer' },
		inAmount: { type: 'string' },
		outAmount: { type: 'string' },
		inVaultAmountBefore: { type: 'string' },
		outVaultAmountBefore: { type: 'string' },
		inFundVaultAmountAfter: { type: 'string' },
		outFundVaultAmountAfter: { type: 'string' },
		inIfTotalSharesBefore: { type: 'string' },
		outIfTotalSharesBefore: { type: 'string' },
		inIfTotalSharesAfter: { type: 'string' },
		outIfTotalSharesAfter: { type: 'string' },
		inIfUserSharesBefore: { type: 'string' },
		outIfUserSharesBefore: { type: 'string' },
		inIfUserSharesAfter: { type: 'string' },
		outIfUserSharesAfter: { type: 'string' },
		outOraclePrice: { type: 'string' },
		outOraclePriceTwap: { type: 'string' },
		rebalanceConfig: { type: 'string' },
	},
	required: [
		'ts',
		'txSig',
		'txSigIndex',
		'slot',
		'inMarketIndex',
		'outMarketIndex',
		'inAmount',
		'outAmount',
		'inVaultAmountBefore',
		'outVaultAmountBefore',
		'inFundVaultAmountAfter',
		'outFundVaultAmountAfter',
		'inIfTotalSharesBefore',
		'outIfTotalSharesBefore',
		'inIfTotalSharesAfter',
		'outIfTotalSharesAfter',
		'inIfUserSharesBefore',
		'outIfUserSharesBefore',
		'inIfUserSharesAfter',
		'outIfUserSharesAfter',
		'outOraclePrice',
		'outOraclePriceTwap',
		'rebalanceConfig',
	],
} as const;

export const claimSchema = {
	type: 'object',
	properties: {
		campaignId: { type: 'string' },
		authorityId: { type: 'string' },
		claimType: { type: 'string', nullable: true },
		status: {
			anyOf: [{ type: 'string', enum: Object.values(ClaimStatus) }, { type: 'null' }],
		},
		amount: { type: 'number', nullable: true },
		assetSymbol: { type: 'string', nullable: true },
		progressAmount: { type: 'number', nullable: true },
		progressCap: { type: 'number', nullable: true },
		claimableAmount: { type: 'number', nullable: true },
		claimedAmount: { type: 'number', nullable: true },
		lastSyncedAt: { type: 'integer', nullable: true },
		campaignEndTs: { type: 'integer', nullable: true },
		processedAt: { type: 'integer', nullable: true },
		targetUserAccount: { type: 'string', nullable: true },
	},
	required: ['campaignId', 'authorityId', 'status'],
} as const;
