services:
  velocity:
    image: velocity-dev
    volumes:
      - ../:/workdir
      - velocity-target:/workdir/target
    environment:
      - ANCHOR_WALLET=/root/.config/solana/id.json
      - RUST_LOG=solana_runtime::message_processor::stable_log=debug
    command: tail -f /dev/null

volumes:
  velocity-target:
