use std::path::Path;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    if std::env::var("DOCS_RS").is_ok() {
        println!("cargo:warning=docs.rs build detected. skipping idl-gen");
        return Ok(());
    }
    let current_dir = std::env::current_dir()?.canonicalize()?;

    // Generate IDL types from the canonical program IDL committed under the SDK
    // package, regenerated by `bun run program:idl`. This is the single source of
    // truth shared with the TypeScript SDK. (Pre-monorepo, velocity-rs lived in a
    // separate repo and vendored a fetched copy under res/velocity.json; the
    // monorepo makes that copy — and its drift — unnecessary.)
    let idl_source_path = current_dir.join("../../packages/sdk/src/idl/velocity.json");
    let idl_mod_path = current_dir.join("crates/src/velocity_idl.rs");
    println!("cargo:rerun-if-changed=../../packages/sdk/src/idl/velocity.json");
    generate_idl_types(&idl_source_path, idl_mod_path.as_path())?;
    Ok(())
}

fn generate_idl_types(
    idl_source_path: &Path,
    idl_mod_path: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let idl_mod_rs = velocity_idl_gen::generate_rust_types(idl_source_path)
        .map_err(|err| format!("generating IDL failed: {err:?}"))?;

    std::fs::write(idl_mod_path, idl_mod_rs)?;
    Ok(())
}
