import {
	BaseDynamoRecord,
	CandleRecord,
	DepositRecord,
	EntityTypes,
	FundingPaymentRecord,
	FundingRateRecord,
	IngestionSource,
	InsuranceFundRecord,
	InsuranceFundStakeRecord,
	LiquidationRecord,
	LPMintRedeemRecord,
	LPRecord,
	OrderActionRecord,
	OrderRecord,
	PositionHistoryRecord,
	ReferralSnapshotRecord,
	SerializedMarketFilter,
	SettlePnlRecord,
	SwapRecord,
	TradeSnapshotRecord,
	TriggerOrderFillStats,
	VaultDepositorSnapshotRecord,
} from '@backend/common';

export const createMockDepositRecord = (
	overrides: Partial<DepositRecord & BaseDynamoRecord> = {}
): DepositRecord & BaseDynamoRecord => ({
	pk: 'test',
	sk: '123',
	ts: 1234567890,
	txSig: 'mock-tx-sig',
	txSigIndex: 1,
	slot: 100000,
	amount: 1000,
	oraclePrice: 1.5,
	marketDepositBalance: 5000,
	marketWithdrawBalance: 3000,
	marketCumulativeDepositInterest: 100,
	marketCumulativeBorrowInterest: 50,
	totalDepositsAfter: 6000,
	totalWithdrawsAfter: 4000,
	depositRecordId: 'mock-deposit-record-id',
	userAuthority: 'mock-user-authority',
	user: 'mock-user',
	direction: 'deposit',
	marketIndex: 0,
	explanation: 'Mock deposit record',
	entity: EntityTypes.User,
	source: IngestionSource.SEQUENTIAL,
	symbol: 'USDC',
	...overrides,
});

export const createMockSettlePnlRecord = (
	overrides: Partial<SettlePnlRecord & BaseDynamoRecord> = {}
): SettlePnlRecord & BaseDynamoRecord => ({
	pk: 'USER#test',
	sk: 'SETTLE_PNL#123',
	ts: 1234567890,
	txSig: 'mock-tx-sig',
	txSigIndex: 1,
	slot: 100000,
	user: 'mock-user',
	pnl: 1000,
	baseAssetAmount: 100,
	quoteAssetAmountAfter: 1000,
	quoteEntryAmount: 900,
	settlePrice: 150,
	marketIndex: 0,
	explanation: 'PNL settled',
	entity: EntityTypes.User,
	source: IngestionSource.SEQUENTIAL,
	...overrides,
});

export const createMockFundingPaymentRecord = (
	overrides: Partial<FundingPaymentRecord & BaseDynamoRecord> = {}
): FundingPaymentRecord & BaseDynamoRecord => ({
	pk: 'USER#test',
	sk: 'FUNDING_PAYMENT#123',
	ts: 1234567890,
	txSig: 'mock-tx-sig',
	txSigIndex: 1,
	slot: 100000,
	userAuthority: 'mock-user-authority',
	user: 'mock-user',
	marketIndex: 0,
	fundingPayment: 100,
	baseAssetAmount: 1000,
	userLastCumulativeFunding: 500,
	ammCumulativeFundingLong: 600,
	entity: EntityTypes.User,
	source: IngestionSource.SEQUENTIAL,
	ammCumulativeFundingShort: 400,
	...overrides,
});

export const createMockLiquidationRecord = (
	overrides: Partial<LiquidationRecord & BaseDynamoRecord> = {}
): LiquidationRecord & BaseDynamoRecord => ({
	pk: 'USER#test',
	sk: 'LIQUIDATION#123',
	ts: 1234567890,
	txSig: 'mock-tx-sig',
	txSigIndex: 1,
	slot: 100000,
	liquidationType: 'partial',
	user: 'mock-user',
	liquidator: 'mock-liquidator',
	marginRequirement: 1000,
	totalCollateral: 900,
	marginFreed: 100,
	liquidationId: 'mock-liquidation-id',
	bankrupt: false,
	canceledOrderIds: ['order-1', 'order-2'],
	liquidatePerp_marketIndex: 0,
	liquidatePerp_oraclePrice: 150,
	liquidatePerp_baseAssetAmount: 100,
	liquidatePerp_quoteAssetAmount: 15000,
	liquidatePerp_lpShares: 0,
	liquidatePerp_fillRecordId: 'fill-record-id',
	liquidatePerp_userOrderId: 'user-order-id',
	liquidatePerp_liquidatorOrderId: 'liquidator-order-id',
	liquidatePerp_liquidatorFee: 50,
	liquidatePerp_ifFee: 25,
	liquidateSpot_assetMarketIndex: 1,
	liquidateSpot_assetPrice: 1.5,
	liquidateSpot_assetTransfer: 1000,
	liquidateSpot_liabilityMarketIndex: 2,
	liquidateSpot_liabilityPrice: 1,
	liquidateSpot_liabilityTransfer: 1500,
	liquidateSpot_ifFee: 10,
	liquidateBorrowForPerpPnl_perpMarketIndex: 3,
	liquidateBorrowForPerpPnl_marketOraclePrice: 200,
	liquidateBorrowForPerpPnl_pnlTransfer: 2000,
	liquidateBorrowForPerpPnl_liabilityMarketIndex: 4,
	liquidateBorrowForPerpPnl_liabilityPrice: 1.2,
	liquidateBorrowForPerpPnl_liabilityTransfer: 2400,
	liquidatePerpPnlForDeposit_perpMarketIndex: 5,
	liquidatePerpPnlForDeposit_marketOraclePrice: 250,
	liquidatePerpPnlForDeposit_pnlTransfer: 2500,
	liquidatePerpPnlForDeposit_assetMarketIndex: 0,
	liquidatePerpPnlForDeposit_assetPrice: 1.8,
	liquidatePerpPnlForDeposit_assetTransfer: 1389,
	perpBankruptcy_marketIndex: 7,
	perpBankruptcy_pnl: -5000,
	perpBankruptcy_ifPayment: 4000,
	perpBankruptcy_clawbackUser: 'clawback-user',
	perpBankruptcy_clawbackUserPayment: 1000,
	perpBankruptcy_cumulativeFundingRateDelta: 0.001,
	spotBankruptcy_marketIndex: 8,
	spotBankruptcy_borrowAmount: 3000,
	spotBankruptcy_ifPayment: 2800,
	spotBankruptcy_cumulativeDepositInterestDelta: 0.005,
	entity: EntityTypes.User,
	source: IngestionSource.SEQUENTIAL,
	...overrides,
});

export const createMockLPRecord = (
	overrides: Partial<LPRecord & BaseDynamoRecord> = {}
): LPRecord & BaseDynamoRecord => ({
	pk: 'USER#test',
	sk: 'LP#123',
	ts: 1234567890,
	txSig: 'mock-tx-sig',
	txSigIndex: 1,
	slot: 100000,
	user: 'mock-user',
	action: 'add',
	marketIndex: 0,
	nShares: 100,
	deltaBaseAssetAmount: 1000,
	deltaQuoteAssetAmount: 150000,
	pnl: 500,
	entity: EntityTypes.User,
	source: IngestionSource.SEQUENTIAL,
	...overrides,
});

export const createMockInsuranceFundStakeRecord = (
	overrides: Partial<InsuranceFundStakeRecord & BaseDynamoRecord> = {}
): InsuranceFundStakeRecord & BaseDynamoRecord => ({
	pk: 'USER#test',
	sk: 'INSURANCE_FUND_STAKE#123',
	ts: 1234567890,
	txSig: 'mock-tx-sig',
	txSigIndex: 1,
	slot: 100000,
	amount: 1000,
	userAuthority: 'mock-user-authority',
	action: 'stake',
	marketIndex: 0,
	ifSharesBefore: 500,
	userIfSharesBefore: 100,
	totalIfSharesBefore: 1000,
	ifSharesAfter: 600,
	userIfSharesAfter: 200,
	totalIfSharesAfter: 1100,
	insuranceVaultAmountBefore: 10000,
	entity: EntityTypes.Authority,
	source: IngestionSource.SEQUENTIAL,
	symbol: 'SOL-PERP',
	...overrides,
});

export const createMockInsuranceFundRecord = (
	overrides: Partial<InsuranceFundRecord & BaseDynamoRecord> = {}
): InsuranceFundRecord & BaseDynamoRecord => ({
	pk: 'MARKET#test',
	sk: 'INSURANCE_FUND#123',
	ts: 1234567890,
	txSig: 'mock-tx-sig',
	txSigIndex: 1,
	slot: 100000,
	spotMarketIndex: 0,
	perpMarketIndex: 1,
	userIfFactor: 0.1,
	totalIfFactor: 1,
	symbol: 'BTC',
	vaultAmountBefore: 100000,
	insuranceVaultAmountBefore: 10000,
	totalIfSharesBefore: 1000,
	totalIfSharesAfter: 1100,
	amount: 1000,
	entity: EntityTypes.Market,
	source: IngestionSource.SEQUENTIAL,
	...overrides,
});

export const createMockFundingRateRecord = (
	overrides: Partial<FundingRateRecord & BaseDynamoRecord> = {}
): FundingRateRecord & BaseDynamoRecord => ({
	pk: 'MARKET#test',
	sk: 'FUNDING_RATE#123',
	ts: 1234567890,
	txSig: 'mock-tx-sig',
	txSigIndex: 1,
	slot: 100000,
	recordId: 'funding-rate-record-id',
	marketIndex: 0,
	symbol: 'BTC',
	fundingRate: 0.0001,
	fundingRateLong: 0.0001,
	fundingRateShort: -0.0001,
	cumulativeFundingRateLong: 0.01,
	cumulativeFundingRateShort: -0.01,
	oraclePriceTwap: 30000,
	markPriceTwap: 30010,
	periodRevenue: 1000,
	baseAssetAmountWithAmm: 100000,
	baseAssetAmountWithUnsettledLp: 10000,
	entity: EntityTypes.Market,
	source: IngestionSource.SEQUENTIAL,
	...overrides,
});

export const createMockOrderActionRecord = (
	overrides: Partial<OrderActionRecord & BaseDynamoRecord> = {}
): OrderActionRecord & BaseDynamoRecord => ({
	pk: 'MARKET#SOL',
	sk: 'ORDER#123',
	ts: 1634567890,
	txSig: 'mock-tx-sig-123456',
	txSigIndex: 0,
	slot: 100000000,
	fillerReward: 0.1,
	baseAssetAmountFilled: 1.5,
	quoteAssetAmountFilled: 45000,
	takerFee: 0.05,
	makerRebate: 0.02,
	referrerReward: 0.01,
	quoteAssetAmountSurplus: 0,
	takerOrderBaseAssetAmount: 2,
	takerOrderCumulativeBaseAssetAmountFilled: 1.5,
	takerOrderCumulativeQuoteAssetAmountFilled: 45000,
	makerOrderBaseAssetAmount: 5,
	makerOrderCumulativeBaseAssetAmountFilled: 3,
	makerOrderCumulativeQuoteAssetAmountFilled: 90000,
	oraclePrice: 30000,
	makerFee: 0.03,
	action: 'fill',
	actionExplanation: 'Order filled',
	marketIndex: 0,
	marketType: 'perp',
	filler: 'filler-pubkey-123',
	fillRecordId: 'fill-record-123',
	taker: 'taker-pubkey-456',
	takerOrderId: 'taker-order-789',
	takerOrderDirection: 'long',
	maker: 'maker-pubkey-789',
	makerOrderId: 'maker-order-012',
	makerOrderDirection: 'short',
	spotFulfillmentMethodFee: 0,
	user: 'user-pubkey-345',
	userOrderId: 123,
	symbol: 'SOL',
	entity: EntityTypes.User,
	source: IngestionSource.SEQUENTIAL,
	marketFilter: SerializedMarketFilter.PERP,
	bitFlags: 0,
	...overrides,
});

export const createMockSwapRecord = (
	overrides: Partial<SwapRecord & BaseDynamoRecord> = {}
): SwapRecord & BaseDynamoRecord => ({
	pk: 'USER#user-pubkey-345',
	sk: 'SWAP#TS#1634567890000#SIG#mock-tx-sig-123456#INDEX#0',
	ts: 1634567890,
	txSig: 'mock-tx-sig-123456',
	txSigIndex: 0,
	slot: 100000000,
	user: 'user-pubkey-345',
	amountOut: 100,
	amountIn: 95,
	outMarketIndex: 1,
	inMarketIndex: 0,
	inSymbol: 'USDC',
	outSymbol: 'SOL',
	outOraclePrice: 30000,
	inOraclePrice: 1,
	fee: 0.1,
	entity: EntityTypes.User,
	source: IngestionSource.SEQUENTIAL,
	...overrides,
});

export const createMockOrderRecord = (
	overrides: Partial<OrderRecord & BaseDynamoRecord> = {}
): OrderRecord & BaseDynamoRecord => ({
	pk: 'USER#testuser',
	sk: 'ORDER#TYPE#PERP',
	ts: 1234567890,
	txSig: 'abc123',
	txSigIndex: 0,
	slot: 12345,
	user: 'testuser',
	status: 'open',
	orderType: 'LIMIT',
	marketType: 'perp',
	orderId: 123,
	userOrderId: 456,
	marketIndex: 1,
	price: 50000,
	baseAssetAmount: 1,
	quoteAssetAmount: 50000,
	baseAssetAmountFilled: 0,
	quoteAssetAmountFilled: 0,
	direction: 'LONG',
	reduceOnly: false,
	triggerPrice: 0,
	triggerCondition: 'ABOVE',
	existingPositionDirection: 'LONG',
	postOnly: false,
	immediateOrCancel: false,
	oraclePriceOffset: 0,
	auctionDuration: 0,
	auctionStartPrice: 0,
	auctionEndPrice: 0,
	maxTs: 1234567890,
	symbol: 'BTC-PERP',
	entity: EntityTypes.User,
	source: IngestionSource.SEQUENTIAL,
	marketFilter: SerializedMarketFilter.PERP,
	...overrides,
});

export const createMockCandleRecord = (
	overrides: Partial<CandleRecord & BaseDynamoRecord> = {}
): CandleRecord & BaseDynamoRecord => ({
	pk: 'CANDLE#SOL-PERP#1',
	sk: '1000',
	ts: 1000,
	fillOpen: 100,
	fillHigh: 105,
	fillLow: 95,
	fillClose: 102,
	oracleOpen: 100,
	oracleHigh: 105,
	oracleLow: 95,
	oracleClose: 102,
	resolution: '1',
	baseVolume: 1000,
	quoteVolume: 25000,
	symbol: 'SOL',
	...overrides,
});

export function createMockVaultDepositorSnapshotRecord(
	overrides: Partial<VaultDepositorSnapshotRecord & BaseDynamoRecord> = {}
) {
	return {
		pk: `USER#123`,
		sk: `SNAPSHOT#1231231`,
		authority: 'mock-authority',
		user: 'mock-user',
		vault: 'vault',
		ts: 1234567890,
		marketIndex: 0,
		totalAccountValue: 1000,
		totalAccountBaseValue: 10,
		ttl: 1734567890,
		...overrides,
	};
}

export function createMockReferralSnapshotRecord(
	overrides: Partial<ReferralSnapshotRecord & BaseDynamoRecord> = {}
) {
	return {
		pk: `AUTHORITY#123`,
		sk: `SNAPSHOT#1231231`,
		authority: 'mock-authority',
		ts: 1234567890,
		ttl: 1734567890,
		referralRewards: '123.123',
		referralCount: '1',
		referredUsers: ['1233112', '123123'],
		referredVolume30D: '123.123123123',
		...overrides,
	};
}

export function createMockEarnSnapshotRecord(
	overrides: Partial<VaultDepositorSnapshotRecord & BaseDynamoRecord> = {}
) {
	return {
		pk: `USER#123`,
		sk: `SNAPSHOT#1231231`,
		authority: 'mock-authority',
		user: 'mock-user',
		ts: 1234567890,
		ttl: 1734567890,
		assets: [
			{
				marketIndex: 0,
				balance: 0,
				deposits: 0,
				withdrawals: 0,
				pnl: 0,
				interestBaseValue: 0,
				interestQuoteValue: 0,
				oraclePrice: 0,
			},
			{
				marketIndex: 0,
				balance: 1090,
				deposits: 0,
				withdrawals: 10,
				pnl: 0,
				interestBaseValue: 0,
				interestQuoteValue: 0,
				oraclePrice: 0,
			},
		],
		...overrides,
	};
}

export function createMockTradingSnapshotRecord(
	overrides: Partial<TradeSnapshotRecord & BaseDynamoRecord> = {}
) {
	return {
		pk: `USER#123`,
		sk: `SNAPSHOT#1231231`,
		authority: 'mock-authority',
		user: 'mock-user',
		unrealizedPnl: 123.12,
		ts: 1234567890,
		ttl: 1734567890,
		...overrides,
	};
}

export const createMockVault = (overrides = {}) => {
	return {
		pubkey: 'mock-vault-pubkey',
		manager: 'mock-manager',
		tokenAccount: 'mock-token-account',
		userStats: 'mock-user-stats',
		user: 'mock-user',
		delegate: 'mock-delegate',
		liquidationDelegate: 'mock-liquidation-delegate',
		userShares: 201982974,
		totalShares: 201982974,
		sharesBase: 0,
		lastFeeUpdateTs: 1741660938,
		liquidationStartTs: 0,
		redeemPeriod: 300,
		initTs: 1741606262,
		totalWithdrawRequested: 0,
		maxTokens: 5000,
		netDeposits: 200.989703,
		totalDeposits: 200.989703,
		totalWithdraws: 0,
		managerNetDeposits: 0,
		managerTotalDeposits: 0,
		managerTotalWithdraws: 0,
		managerTotalFee: 0,
		managerTotalProfitShare: 0,
		lastManagerWithdrawRequest: { shares: 0, value: 0, ts: 0 },
		minDepositAmount: 1,
		profitShare: 0,
		managementFee: 0,
		hurdleRate: 0,
		spotMarketIndex: 0,
		permissioned: false,
		...overrides,
	};
};

export const createMockTriggerOrderFillStats = (
	overrides: Partial<TriggerOrderFillStats & BaseDynamoRecord> = {}
): TriggerOrderFillStats & BaseDynamoRecord => ({
	pk: 'ANALYTICS#TRIGGER_ORDER_FILL#SOL-PERP',
	sk: '1738637201',
	marketType: 'perp',
	marketIndex: '0',
	market: 'SOL-PERP',
	orderType: 'all',
	cohort: '0',
	slotsToFillP10: '5',
	slotsToFillP25: '8',
	slotsToFillP50: '12',
	slotsToFillP75: '18',
	slotsToFillP99: '45',
	slotsToFillMax: '120',
	slotsToFillAvg: '15.5',
	fillVsTriggerMin: '-2.5',
	fillVsTriggerMax: '8.2',
	fillVsTriggerAvg: '1.8',
	fillVsTriggerP10: '-1.2',
	fillVsTriggerP25: '0.5',
	fillVsTriggerP50: '1.5',
	fillVsTriggerP75: '3.2',
	fillVsTriggerP99: '7.8',
	triggerMarketCount: '45',
	triggerLimitCount: '23',
	totalTriggeredOrders: '68',
	reduceOnlyCount: '12',
	nonReduceOnlyCount: '56',
	...overrides,
});

export const createMockPositionRecord = (
	overrides: Partial<PositionHistoryRecord & BaseDynamoRecord> = {}
): PositionHistoryRecord & BaseDynamoRecord => ({
	pk: 'USER#test',
	sk: 'POSITION#123',
	ts: 1234567890,
	txSig: 'mock-tx-sig',
	txSigIndex: 1,
	slot: 100000,
	user: 'maker-pubkey-789',
	marketIndex: 0,
	symbol: 'SOL',
	baseAssetAmountFilled: 1.5,
	quoteAssetAmountFilled: 1500,
	userExistingBaseAssetAmount: 1.5,
	userExistingQuoteEntryAmount: 1500,
	takerFee: 1.5,
	makerFee: 0.75,
	entity: EntityTypes.User,
	baseClosedForPnl: 1.5,
	userFee: 1.5,
	fillerReward: 0.1,
	marketType: 'perp',
	filler: 'filler-pubkey-123',
	fillRecordId: 'fill-record-123',
	taker: 'taker-pubkey-456',
	takerOrderId: 'taker-order-789',
	takerOrderDirection: 'long',
	maker: 'maker-pubkey-789',
	makerOrderId: 'maker-order-012',
	makerOrderDirection: 'short',
	spotFulfillmentMethodFee: 0,
	takerExistingQuoteEntryAmount: 1500,
	takerExistingBaseAssetAmount: 1.5,
	makerExistingBaseAssetAmount: 1.5,
	makerExistingQuoteEntryAmount: 1500,
	makerRebate: 0.02,
	referrerReward: 0.01,
	quoteAssetAmountSurplus: 0,
	takerOrderBaseAssetAmount: 2,
	takerOrderCumulativeBaseAssetAmountFilled: 1.5,
	takerOrderCumulativeQuoteAssetAmountFilled: 45000,
	makerOrderBaseAssetAmount: 5,
	makerOrderCumulativeBaseAssetAmountFilled: 3,
	makerOrderCumulativeQuoteAssetAmountFilled: 90000,
	oraclePrice: 30000,
	action: 'fill',
	actionExplanation: 'Order filled',
	source: IngestionSource.SEQUENTIAL,
	marketFilter: SerializedMarketFilter.PERP,
	bitFlags: 0,
	...overrides,
});

export const createMockPoolSnapshotRecord = (overrides = {}) => ({
	ts: 1234567890,
	ttl: 1741950000,
	pool: '1',
	tvl: '1234567.890000',
	price: '1.234567',
	isDaily: true,
	...overrides,
});

export function createMockLPMintRedeemRecord(
	overrides = {}
): LPMintRedeemRecord & BaseDynamoRecord {
	return {
		pk: 'AUTHORITY#test',
		sk: 'LP#123',
		ts: 1762893737,
		slot: 379450944,
		authority: 'auth1',
		description: 1,
		amount: 1,
		fee: 0.0000898,
		spotMarketIndex: 1,
		constituentIndex: 1,
		oraclePrice: 0.156510305,
		mint: 'So11111111111111111111111111111111111111112',
		lpAmount: 0.000017193572,
		lpFee: 0.000005158,
		lpPrice: 0.000909466,
		mintRedeemId: '6',
		lastAum: 32.641738077,
		lastAumSlot: 379450944,
		inMarketCurrentWeight: 0.00028342,
		inMarketTargetWeight: -0.000239854,
		lpPool: 'ELgW8UwFRAUc7YpRMzJiuVVwSFmPHMW9knY6hBx9vRxa',
		txSig: 'dq1jUnV1fKdnnrM9n4nuXDD6TUirs5FMdsDsH2c6FdmXTBdEugEmmnuxAFf9GGz5zdimPYDNhEu2vtMMhqBCmC6',
		txSigIndex: 1,
		source: IngestionSource.SEQUENTIAL,
		entity: EntityTypes.Authority,
		...overrides,
	};
}
