#!/bin/sh
exit 0 # skip husky for now
. "$(dirname "$0")/_/husky.sh"

bun run prettify
bun run lint

if [ -z "$TS_PRECOMMIT_ONLY" ] || [ "$TS_PRECOMMIT_ONLY" = "false" ]; then
  cargo fmt -- --check
fi
